# Generated by Django 3.1.1 on 2020-10-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=25)),
            ],
        ),
    ]
